# Generated by Django 4.1.5 on 2023-05-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.IntegerField(choices=[[0, 'Asesoría Técnica'], [1, 'Concepto Técnico'], [2, 'Instalación Equipo'], [3, 'Instalación Hardware'], [4, 'Instalación Software'], [5, 'Instalación Preiféricos'], [6, 'Mantenimiento Preventivo'], [7, 'Revisión equipo de Computo'], [8, 'Revisión Periferico'], [9, 'Videoconferencia']]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.CharField(max_length=200),
        ),
    ]
