# Generated by Django 4.1.5 on 2023-05-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_contacto_tipo_consulta_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('cargo', models.CharField(max_length=50)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Asesoría Técnica'], [1, 'Concepto Técnico'], [2, 'Instalación Equipo'], [3, 'Instalación Hardware'], [4, 'Instalación Software'], [5, 'Instalación Preiféricos'], [6, 'Mantenimiento Preventivo'], [7, 'Revisión equipo de Computo'], [8, 'Revisión Periferico'], [9, 'Videoconferencia']])),
                ('mensaje', models.TextField()),
                ('avisos', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.CharField(max_length=100),
        ),
    ]
